"use strict";var isMobile={Android:function(){return navigator.userAgent.match(/Android/i);},BlackBerry:function(){return navigator.userAgent.match(/BlackBerry/i);},iOS:function(){return navigator.userAgent.match(/iPhone|iPad|iPod/i);},Opera:function(){return navigator.userAgent.match(/Opera Mini/i);},Windows:function(){return navigator.userAgent.match(/IEMobile/i);},any:function(){return(isMobile.Android()||isMobile.BlackBerry()||isMobile.iOS()||isMobile.Opera()||isMobile.Windows());}};function equalheight(container){var currentTallest=0,currentRowStart=0,rowDivs=new Array(),$el,topPosition=0,topPostion=0,currentDiv=0;$(container).each(function(){$el=$(this);$($el).height('auto')
topPostion=$el.position().top;if(currentRowStart!=topPostion){for(currentDiv=0;currentDiv<rowDivs.length;currentDiv++){rowDivs[currentDiv].height(currentTallest);}
rowDivs.length=0;currentRowStart=topPostion;currentTallest=$el.height();rowDivs.push($el);}else{rowDivs.push($el);currentTallest=(currentTallest<$el.height())?($el.height()):(currentTallest);}
for(currentDiv=0;currentDiv<rowDivs.length;currentDiv++){rowDivs[currentDiv].height(currentTallest);}});}
function doAnimations(elems){var animEndEv='webkitAnimationEnd animationend';elems.each(function(){var $this=$(this),$animationType=$this.data('animation');$this.addClass($animationType).one(animEndEv,function(){$this.removeClass($animationType);});});}
function expertinfo(){var mem_hgt=$('.member').height();$('.member .info').stop(true,true).css({"height":mem_hgt,"top":mem_hgt});}
function vCenterAlign(elm){var parentHeight=$(elm).parent().height();var topVal=parentHeight/2;var elmWid=$(elm).width();var elmWidHalf=elmWid/2;$(elm).css({"margin-top":"-"+elmWidHalf+"px","margin-left":"-"+elmWidHalf+"px","top":topVal+"px"});}
function resetStellar(){var section=$('.offer');var secPosition=section.position();var curSecPos=section.position.top;setTimeout(function(){if(secPosition!=curSecPos){$(window).data('plugin_stellar').destroy();$(window).data('plugin_stellar').init();$(window).data('plugin_stellar').refresh();$.stellar('refresh');}},0);}
function menuEdgeFilter(elem){var elm=$(elem).parent().find('ul.dropdown-menu');var off=elm.offset();var l=off.left;var w=elm.width();var docH=$("header").height();var docW=$("header").width();var isEntirelyVisible=(l+ w<=docW);if(elm.length>0){if(!isEntirelyVisible){$(elem).parent().addClass('edge');$(elem).parent().parent().addClass('edge');}else{$(elem).parent().removeClass('edge');}}}
(function($){var preLodr=$('#preloader');if(preLodr.length>0){$('#preloader').fadeOut();$('.loading').delay(350).fadeOut('slow');$('body').delay(350).css({'overflow':'visible'});}
$(window).on("scroll",function(){if($(window).scrollTop()>1000){$('a.top').fadeIn('slow');}else{$('a.top').fadeOut('slow');}
if($('.header5').length>0){if($(window).scrollTop()>150){var Headertop=$('.header-top').height();$('header.header5.affix').css('top','-'+Headertop+'px');}else if($(window).scrollTop()<150){var navbarHeader=$('.navbar-header').height();$('header.header5.affix').css('top','0');}}});$(window).on("load",function(){var winW=$('body').width();var drpDown=$('.dropdown');var searchF=$('#search');var member=$('.member');var carousel=$('.carousel');var navTabs=$('.nav-tabs');var accordion=$('.panel');var formField=$('input, textarea, email, tel');var prettyPhoto=$("a[data-rel^='prettyPhoto']");var dtpicker=$('#datetimepicker');var svgAlign=$('.svg');var singleSlide=$('#slides').hasClass('singleSlide');var cfSlide=$('#cfSlide');var siteMap=$('.sitemap');setTimeout(function(){equalheight('.listBox, .equal, .quote');},100);setTimeout(function(){$('.stat').waypoint(function(){$('.timer').countTo({refreshInterval:10});},{offset:'90%'});},10);if(drpDown.length>0){$('.navbar-nav').on("mouseover",function(e){if($(e.target).is('a')&&$(e.target).parent().hasClass('dropdown')){var ths=$(e.target);menuEdgeFilter(ths);}});}
if(searchF.length>0){$('a[href="#search"]').on('click',function(event){$('#search').addClass('open');$('#search > form > input[type="search"]').focus();});$('#search').on('click keyup',function(event){if(event.target==this||event.keyCode===27){$('#search').removeClass('open');}});$('#search .close').on('click',function(event){$('#search').removeClass('open');});}
if(winW<=767){$("a.top[href^=\\#], a.smooth[href^=\\#]").on("click",function(event){event.preventDefault();$('html,body').animate({scrollTop:$(this.hash).offset().top- 470},1000);});}else{$("a.top[href^=\\#], a.smooth[href^=\\#]").on("click",function(event){event.preventDefault();$('html,body').animate({scrollTop:$(this.hash).offset().top- 0},1000);});}
if(carousel){$('#image-slider.carousel').carousel({interval:7000});$('#testimonial.carousel').carousel({interval:7000});$('#post-slider.carousel').carousel({interval:5500});var $myCarousel=$('#image-slider'),$firstAnimatingElems=$myCarousel.find('.item:first').find("[data-animation ^= 'animated']");$myCarousel.carousel();doAnimations($firstAnimatingElems);$myCarousel.carousel('pause');$myCarousel.on('slide.bs.carousel',function(e){var $animatingElems=$(e.relatedTarget).find("[data-animation ^= 'animated']");doAnimations($animatingElems);});}
if($('.grid')){var $grid=$('.grid').isotope({itemSelector:'.grid-item',percentPosition:true,});$grid.imagesLoaded().progress(function(){$grid.isotope('layout');});$('.button-group').on('click','button',function(){var filterValue=$(this).attr('data-filter');$grid.isotope({filter:filterValue});});$('.button-group').each(function(i,buttonGroup){var $buttonGroup=$(buttonGroup);$buttonGroup.on('click','button',function(){$buttonGroup.find('.active').removeClass('active');$(this).addClass('active');});});}
var Hom=$('#home');if(Hom){var hHeight=$('#home').outerHeight();$('.breadcrumbs, #image-slider').not("#home.header4 + .breadcrumbs").css('margin-top',hHeight);}
if(member){setTimeout(function(){expertinfo();},2000);}
if(navTabs){$('.nav-tabs a').on("click",function(e){e.preventDefault();$(this).tab('show');var cTab=$(this).attr('href');equalheight($(cTab).find('.listBox'));});$('a[data-toggle="tab"]').on('shown.bs.tab',function(e){equalheight('.listBox');});}
if(accordion){$('.panel-title a').on("click",(function(){var thisParent=$(this).parent().parent().next();if(thisParent.hasClass('in')){$(this).parent().removeClass('active');}else{$('.panel-title').removeClass('active');$(this).parent().addClass('active');}}));}
if(formField){$('input, textarea').placeholder();}
if(prettyPhoto){$("a[data-rel^='prettyPhoto']").prettyPhoto({overlay_gallery:true});}
if(dtpicker){$('#datetimepicker').datetimepicker({format:'m.d.Y H:i',inline:false,lang:'en'});}
$('.button-group button').on('click',function(e){e.preventDefault();resetStellar();});$('.servicesList .nav-tabs li a').on('click',function(e){e.preventDefault();resetStellar();});if(cfSlide.length>0){$("#cfSlide").slider({value:1,min:1,max:30,step:1,slide:function(event,ui){$("#cfsVal").val(ui.value);var sval=$("#cfsVal").val();if(sval==30){$('#cfSubmit').removeAttr("disabled");}else{$('#cfSubmit').attr('disabled','disabled');}}});}
if(singleSlide){$('#slides').superslides({play:false,});}else{$('#slides').superslides({animation:'fade',play:9000,animation_speed:600});}
$("#packageSlider").owlCarousel({autoPlay:false,items:1,itemsDesktop:[1400,1],itemsDesktopSmall:[979,1],itemsTablet:[768,1],itemsMobile:[600,1],navigation:true,navigationText:["<img class='svg' src='images/svg/arrow-left-w.svg' onerror='this.src='arrow-left-w.png' alt='Prev' />","<img class='svg' src='images/svg/arrow-right-w.svg' onerror='this.src='arrow-right-w.png'' alt='Next' />"],pagination:false});$("#serviceSlider").owlCarousel({autoPlay:false,items:3,itemsDesktop:[1400,3],itemsDesktopSmall:[979,2],itemsTablet:[768,2],itemsMobile:[600,1],navigation:true,navigationText:["<img class='svg' src='images/svg/arrow-left-w.svg' onerror='this.src='arrow-left-w.png' alt='Prev' />","<img class='svg' src='images/svg/arrow-right-w.svg' onerror='this.src='arrow-right-w.png'' alt='Next' />"],pagination:false});$("#testimonial2").owlCarousel({autoPlay:false,items:2,itemsDesktop:[1400,2],itemsDesktopSmall:[979,2],itemsTablet:[768,1],itemsMobile:[600,1],navigation:true,navigationText:["<img class='svg' src='images/svg/arrow-left-w.svg' onerror='this.src='arrow-left-w.png' alt='Prev' />","<img class='svg' src='images/svg/arrow-right-w.svg' onerror='this.src='arrow-right-w.png'' alt='Next' />"],pagination:false});$("#serviceSliderLanding").owlCarousel({autoPlay:false,items:5,itemsDesktop:[1400,5],itemsDesktopSmall:[979,2],itemsTablet:[768,2],itemsMobile:[600,1],navigation:true,navigationText:["<img class='svg' src='images/svg/arrow-left-w.svg' onerror='this.src='arrow-left-w.png' alt='Prev' />","<img class='svg' src='images/svg/arrow-right-w.svg' onerror='this.src='arrow-right-w.png'' alt='Next' />"],pagination:false});$("#galSlider").owlCarousel({autoPlay:false,items:5,itemsDesktop:[1400,5],itemsDesktopSmall:[979,2],itemsTablet:[768,2],itemsMobile:[600,1],navigation:true,navigationText:["<img class='svg' src='images/svg/arrow-left-w.svg' onerror='this.src='arrow-left-w.png' alt='Prev' />","<img class='svg' src='images/svg/arrow-right-w.svg' onerror='this.src='arrow-right-w.png'' alt='Next' />"],pagination:false});if(svgAlign.length>0){setTimeout(function(){$('figure.grid-item figcaption > a.zoom .svg, .grid-item a.zoom .svg').each(function(){var ths=$(this);vCenterAlign(ths);});},600);$('img.svg').each(function(){var $img=$(this);var imgID=$img.attr('id');var imgClass=$img.attr('class');var imgURL=$img.attr('src');$.get(imgURL,function(data){var $svg=$(data).find('svg');if(typeof imgID!=='undefined'){$svg=$svg.attr('id',imgID);}
if(typeof imgClass!=='undefined'){$svg=$svg.attr('class',imgClass+' replaced-svg');}
$svg=$svg.removeAttr('xmlns:a');$img.replaceWith($svg);},'xml');});}
if(siteMap.length>0){$('ul.sitemap li.dropdown').each(function(){$(this).find('a').on("click",function(e){e.preventDefault();$(this).toggleClass('opened');var opened=$(this).hasClass('opened');if(opened){$('ul.sitemap li').find('.dropdown-menu').slideUp(200);$(this).parent().find('.dropdown-menu').slideDown(200);}else{$('ul.sitemap li').find('.dropdown-menu').slideUp(200);}});});}});$(window).on("resize",function(){var winW=$('body').width();var drpDown=$('.dropdown');var searchF=$('#search');var member=$('.member');var carousel=$('.carousel');var navTabs=$('.nav-tabs');var accordion=$('.panel');var formField=$('input, textarea, email, tel');var prettyPhoto=$("a[data-rel^='prettyPhoto']");var dtpicker=$('#datetimepicker');var svgAlign=$('.svg');var singleSlide=$('#slides').hasClass('singleSlide');var cfSlide=$('#cfSlide');var siteMap=$('.sitemap');equalheight('.listBox, .equal, .quote');if(drpDown.length>0){$('.navbar-nav').find('ul, li').removeClass('edge');$('.navbar-nav').on("mouseover",function(e){if($(e.target).is('a')&&$(e.target).parent().hasClass('dropdown')){var ths=$(e.target);menuEdgeFilter(ths);}});}
if(svgAlign.length>0){setTimeout(function(){$('figure.grid-item figcaption > a.zoom .svg, .grid-item a.zoom .svg').each(function(){var ths=$(this);vCenterAlign(ths);});},600);}});if(!isMobile.any()){$(window).stellar({horizontalScrolling:false,responsive:true});}
var scForm=$('#subscribeForm');if(scForm.length>0){$("#sub-submit").on("click",function(){var proceed=true;var output='';$("#subscribeForm input[required]").each(function(){var email_reg=/^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/;if($(this).attr("type")=="email"&&!email_reg.test($.trim($(this).val()))){$(this).css('border-color','red');proceed=false;}});if(proceed){var post_data={'emailSubscribe':$('input[name=emailSubscribe]').val(),'sub-security':$('input[name=sub-security]').val(),'domain':$(location).attr('href')}
$.post('form/subscribe.php',post_data,function(response){if(response.type=='error'){output='<div class="alert alert-danger alert-dismissible"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>'+response.text+'</div>';}else{output='<div class="alert alert-success alert-dismissible"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>'+response.text+'</div>';$("#subscribeForm  input[required=true]").val('');$("#subscribeForm").slideUp();}
$(".scfs_response").hide().html(output).slideDown();},'json');}});$("#subscribeForm  input[required=true]").keyup(function(){$(this).css('border-color','');$(".scfs_response").slideUp();});}
var cForm=$('#cForm');if(cForm.length>0){$("#cfSubmit").on("click",function(){var proceed=true;var output='';$("#cForm input[required], #cForm textarea[required]").each(function(){$(this).css('border-color','');if(!$.trim($(this).val())){$(this).css('border-color','red');proceed=false;}
var email_reg=/^([\w-\.]+@([\w-]+\.)+[\w-]{2,4})?$/;if($(this).attr("type")=="email"&&!email_reg.test($.trim($(this).val()))){$(this).css('border-color','red');proceed=false;}});if(proceed){var post_data={'name':$('input[name=name]').val(),'email':$('input[name=email]').val(),'phone':$('input[name=phone]').val(),'datetimepicker':$('input[name=datetimepicker]').val(),'message':$('textarea[name=message]').val(),'domain':$(location).attr('href')}
$.post('form/contact.php',post_data,function(response){if(response.type=='error'){output='<div class="alert alert-danger alert-dismissible"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>'+response.text+'</div>';}else{output='<div class="alert alert-success alert-dismissible"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>'+response.text+'</div>';$("#cForm  input[required=true], #cForm textarea[required=true]").val('');$("#cForm").slideUp();}
$(".cfs_response").hide().html(output).slideDown();},'json');}});$("#cForm  input[required=true], #cForm textarea[required=true]").keyup(function(){$(this).css('border-color','');$(".cfs_response").slideUp();});}}(jQuery));